name: Process and Deploy to gh-pages
on:
  push:
    branches:
      - main
    paths:
      - "**/*.ipynb" # Only trigger on notebook changes

jobs:
  process-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install pinned dependencies
        run: |
          pip install --upgrade pip
          pip install notebook==6.5.2 nbconvert==7.2.9 MarkupSafe==2.1.1 jinja2==3.0.3 ipykernel==6.21.2 pipreqs

      - name: Detect changed notebooks
        id: changed-files
        uses: tj-actions/changed-files@v42
        with:
          files: "**/*.ipynb"

      - name: Convert changed notebooks
        if: steps.changed-files.outputs.any_changed == 'true'
        run: |
          for nb in ${{ steps.changed-files.outputs.all_changed_files }}; do
            jupyter nbconvert "$nb" --to markdown --execute --allow-errors
          done

      # No commit/push to main branch here!

      - name: Deploy to gh-pages
        if: steps.changed-files.outputs.any_changed == 'true'
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: .
          clean: false
