name: Process and Deploy to gh-pages
on:
  push:
    branches:
      - main
    paths:
      - "**/*.ipynb"
      - "**/*.md" # Also trigger on markdown file changes

jobs:
  process-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install pipreqs and core notebook tools
        run: |
          pip install --upgrade pip
          pip install notebook==6.5.2 nbconvert==7.2.9 MarkupSafe==2.1.1 jinja2==3.0.3 ipykernel==6.21.2 pipreqs

      - name: Detect changed files
        id: changed-files
        uses: tj-actions/changed-files@v42
        with:
          files: |
            **/*.ipynb
            **/*.md

      - name: Create temp directory for file processing
        run: mkdir -p temp_processing

      - name: Convert changed notebooks to scripts
        if: steps.changed-files.outputs.any_changed == 'true'
        run: |
          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
            if [[ "$file" == *.ipynb ]]; then
              jupyter nbconvert "$file" --to script --output "temp_processing/${file%.ipynb}.py"
            fi
          done

      - name: Generate requirements.txt for changed files
        if: steps.changed-files.outputs.any_changed == 'true'
        run: |
          pipreqs temp_processing --force
          if [ -f temp_processing/requirements.txt ]; then
            mv temp_processing/requirements.txt ./
          fi

      - name: Install notebook dependencies
        if: steps.changed-files.outputs.any_changed == 'true'
        run: |
          if [ -f requirements.txt ]; then
            pip install -r requirements.txt
          fi

      - name: Process changed notebooks and markdown
        if: steps.changed-files.outputs.any_changed == 'true'
        run: |
          # Process changed notebooks
          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
            if [[ "$file" == *.ipynb ]]; then
              jupyter nbconvert "$file" --to markdown --execute --allow-errors
            fi
          done

      - name: Deploy to gh-pages
        if: steps.changed-files.outputs.any_changed == 'true'
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: .
          clean: false

      - name: Cleanup temporary files
        if: always()
        run: |
          # Clean up all temporary files and directories
          rm -rf temp_processing
          find . -name "*.py" -not -path "./.venv/*" -not -path "./.*" -delete
          rm -f requirements.txt || true
