name: jupyter-site-template-deploy
on:
  push:
    branches:
      - main

jobs:
  deploy-gh-pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install system dependencies
        run: sudo apt-get install -y pandoc

      - name: Install core packages (pinned versions)
        run: |
          pip install --upgrade pip
          pip install notebook==6.5.2 nbconvert==7.2.9 \MarkupSafe==2.1.1 jinja2==3.0.3 ipykernel==6.21.2 pipreqs

      - name: Detect notebook dependencies
        run: |
          # Convert notebooks to scripts to detect imports
          find . -name "*.ipynb" -exec jupyter nbconvert {} --to script \;
          # Generate requirements.txt from all scripts
          pipreqs . --mode no-pin --force
          # Clean up temporary scripts
          find . -name "*.py" -not -path "./.venv/*" -delete

      - name: Install notebook dependencies
        run: pip install -r requirements.txt

      - name: Convert notebooks with outputs
        run: |
          export PYTHONPATH="${PYTHONPATH}:${PWD}"
          find . -name "*.ipynb" -exec jupyter nbconvert {} \
            --to markdown \
            --execute \
            --allow-errors \
            --TemplateExporter.exclude_input_prompt=True \;

      - uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: .
