name: jupyter-site-template-deploy
on:
  push:
    branches:
      - main

jobs:
  deploy-gh-pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install dependencies
        run: |
          pip3 install notebook==6.4.12
          pip3 install --upgrade nbconvert
          pip3 install jinja2==3.0.3  # Optional: Only if you want to pin jinja2
          pip3 install nbstripout

      - name: Clean Colab notebooks
        run: find . -name "*.ipynb" -exec nbstripout {} \;

      - name: Convert notebooks
        run: find . -name "*.ipynb" -exec jupyter nbconvert {} --to markdown \;

      - uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: .
